### ISSUE TITLE
Error on importing csv file for eParcel (v2.2.2)

### ISSUE THREAD

**Issue by tspigel-inchoo** [fontis/fontis_australia#11]
On CSV import, the system.log fills up with this error and the admin silently ignores it, saying that the changes were successfully saved (which ofcourse isn't the case):
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'charge_codes_individual' in 'field list'
```

The error can be easily fixed if you edit the app/code/community/Fontis/Australia/Model/Mysql4/Shipping/Carrier/Eparcel.php file and change the lines 307 & 308 into:
```
                            'charge_code_individual' => $csvLine[8],
                            'charge_code_business' => $csvLine[9]
```

**Comment by chnorton** [comment]
Fixed in commit [cdd50da](https://github.com/fontis/fontis_australia/commit/cdd50dabcad889264a4d7efc3a749d68a6e5b986).
