### ISSUE TITLE
Module use Deprecated functionality: Call-time pass-by-reference

### ISSUE THREAD

**Issue by dedmeet** [fontis/fontis_australia#13]
Deprecated functionality: Call-time pass-by-reference has been deprecated  in /home/lucas/workspace/sites/kitchenwarehousenew/app/code/community/Fontis/Australia/Model/FeedCronBase.php on line 150

**Comment by chnorton** [comment]
The feeds generator code has been removed from this extension and moved into its own standalone extension, which can be found here:

https://github.com/fontis/fontis_feedsgenerator

If the problem still exists, we'd appreciate it if you could please submit as a new issue in that repository.
