### ISSUE TITLE
Development and Testing Script on Fontis site does not work for newer version of feeds

### ISSUE THREAD

**Issue by tambick** [fontis/fontis_australia#16]
I have updated to the lastest version of Fontis Australia and wanted to run the cron for the feeds before the midnight set run time. Tried to run this as per your website:

<?php
 
// Define path to Magento
define("MAGE_BASE_DIR", '/path/to/magento');
 
// Kick-start the Magento stack
require_once MAGE_BASE_DIR . '/app/Mage.php';
Mage::app();
 
// Initialise and trigger the MyShopping feed
$model = Mage::getModel('australia/myshopping_cron');
$model->nonstatic();
 
// Initialise and trigger the GetPrice feed
$model = Mage::getModel('australia/getprice_cron');
$model->nonstatic();
 
// Initialise and trigger the Shopbot feed
$model = Mage::getModel('australia/shopbot_cron');
$model->nonstatic();

This now doesn't work. It comes up with the following error:

PHP Fatal error:  Call to undefined method Fontis_Australia_Model_MyShopping_Cron::nonstatic() in /path/to/magento/feed.php on line 12

Are you able to update this script so that we can run it if needed to kick start the cron for feeds prior to the midnight setting?

Thanks!

**Comment by chnorton** [comment]
The feeds generator code has been removed from this extension and moved into its own standalone extension, which can be found here:

https://github.com/fontis/fontis_feedsgenerator

If the problem still exists, we'd appreciate it if you could please submit as a new issue in that repository.
