### ISSUE TITLE
Feed Export (getprice) places special prices that are not within date range

### ISSUE THREAD

**Issue by dedmeet** [fontis/fontis_australia#23]
The feed export is ignoring the Special Price date ranges.

Thus if a product is set to have a special price in the future, or if the Special Price To date is in the past, then the feed still sets the special price.

The end effect is that getprice lists the item with the special price, and not the real price.

**Comment by chnorton** [comment]
The feeds generator code has been removed from this extension and moved into its own standalone extension, which can be found here:

https://github.com/fontis/fontis_feedsgenerator

If the problem still exists, we'd appreciate it if you could please submit as a new issue in that repository.
