### ISSUE TITLE
custom negotiated eParcel charge codes should be allowed

### ISSUE THREAD

**Issue by jonpday** [fontis/fontis_australia#39]
some customers have unique charge costs for eParcel that are not included in `Fontis_Australia_Helper_Eparcel::$chargeCodes`. Options to fix this are either (a) add a System Config value for "allow custom charge code" which `isValidChargeCode` will check if charge code is not found in the private array, or (b) use config XML rather than a private array. Option (b) this would allow developers to specify charge codes in their own module's config.xml to validate the codes uploaded by administrators are still valid.

**Comment by jonathan-dh** [comment]
Hi @jonpday, happy new year!

Sorry I never got around to this, the end of 2014 was hectic. Did you get it working? Any chance you could open a PR? I doubt I'm going to dive into this any time soon unfortunately :(

**Comment by jonpday** [comment]
hiya, we just went with the lightweight solution (https://github.com/aligent/fontis_australia/commit/7a48be62ed757590d973a15ac5315f645a43e1d3) in the end, might revisit if the client needs further changes... happy to PR that if you'd like?

**Comment by jonathan-dh** [comment]
I think that would be enough for most users. @chnorton, what do you think?

**Comment by chnorton** [comment]
Happy to accept a PR for this - the lightweight solution looks fine to me.

**Comment by chnorton** [comment]
Added to 2.6.0 and 3.1.0 versions.

**Comment by behindthepage** [comment]
This throws an error now if the Charge code is one of the standard codes.

```php
$isStandard = in_array($chargeCode, $this->standardChargeCodes);

        if ($isStandard) {
            return true;
        }
        elseif (!$isStandard && Mage::getStoreConfigFlag('doghouse_eparcelexport/charge_codes/allow_custom_charge_codes')) {
```

The code needs to return true if $isStandard

Regards
Geoff

**Comment by jonpday** [comment]
that makes sense @behindthepage - given that this issue has been closed, suggest that you raise a new issue and create a merge request with the change you've sketched then @chnorton can review and incorporate it.
