### ISSUE TITLE
Fatal error in Fontis_Australia_Model_Observer.php on line 23

### ISSUE THREAD

**Issue by TimMarshAU** [fontis/fontis_australia#43]
Manual upload to a CE1.9 build.

Fatal error: require_once(): Failed opening required '/home/gooleys/public_html/mage19/includes/src/../lib/vendor/autoload.php' (include_path='/home/gooleys/public_html/mage19/includes/src:.:/usr/lib/php:/usr/local/lib/php') in /home/gooleys/public_html/mage19/includes/src/Fontis_Australia_Model_Observer.php on line 23

Apologies if this shouldn't be logged here.

**Comment by uditgupta00028** [comment]
I am also getting the same error. How can I fix it. Please help! My website has down.

**Comment by DeathCradle** [comment]
I was getting this error when compiling. Replacing the require_once on line 23 in /app/code/community/Fontis/Australia/Model/Observer.php with the following allowed it to compile and enable without white screening:

require_once(Mage::getBaseDir('base') . '/app/code/community/Fontis/Australia/lib/vendor/autoload.php');
