### ISSUE TITLE
Inaccurate weight sent to AusPost API

### ISSUE THREAD

**Issue by rsiirak** [fontis/fontis_australia#51]
Total cart weight is cast as integer in [Australiapost.php](https://github.com/fontis/fontis_australia/blob/master/src/app/code/community/Fontis/Australia/Model/Shipping/Carrier/Australiapost.php) meaning weights are rounded down.
In the case of weight being under 1kg (e.g. 0.9kg) it is rounded into 0 and sent to the API as the following GET request: https://auspost.com.au/api/postage/parcel/international/service?country_code=JP&weight=0 which receives a 404 status code with the following content {"error":{"errorMessage":"Please enter a valid Weight."}}.
This is an issue as international orders under 1kg would not get any shipping options (unless using other methods).
In addition, casting to integer returns less inaccurate shipping estimations, in some cases resulting in underestimation of the cost.

As a temporary solution I have switched the type to string in both [Australiapost.php](https://github.com/fontis/fontis_australia/blob/master/src/app/code/community/Fontis/Australia/Model/Shipping/Carrier/Australiapost.php) and [auspost-php-api service.json](https://github.com/fontis/auspost-api-php/blob/master/src/Auspost/Postage/service.json).

**Comment by chnorton** [comment]
That code is likely a leftover from the (older) rate calculator which only accepted whole numbers. I'll take a look at what the API will accept - it sounds like you've tested it with decimals and there were no issues?

**Comment by lukegoodwin** [comment]
I seem to be running into the same problem, though not limited to international postal services. Any solutions found?

**Comment by bencorlett** [comment]
Hi all, I have fixed this in #57 and fontis/auspost-api-php#4. As soon as @chnorton merges this in, you'll see your issues disappear.

**Comment by chnorton** [comment]
Hi all! Merging in the second patch from @bencorlett for this issue took an embarrassingly long time (almost a year) so I would like to apologise for that. It has been merged in now though, and version 3.1.7 of the Australia extension has been released here on GitHub and on [our website](https://www.fontis.com.au/australia-magento-extension).
