### ISSUE TITLE
Magento 2 support

### ISSUE THREAD

**Issue by jonpday** [fontis/fontis_australia#56]
Hi @chnorton just wondering whether you had any plans to make this module (or a new version) compatible with Magento 2? Happy to collaborate as we start Mage2 projects in the next month or so just don't want to duplicate efforts.

**Comment by chnorton** [comment]
@jonpday we're actually planning to have a Magento 2 beta release ready to go in January. Will be happy to get feedback on it at that point and continue collaborating from there.

**Comment by jonpday** [comment]
sounds great thx @chnorton are you expecting to replicate all the functionality? I'm particularly interested in the payment methods... :)

**Comment by chnorton** [comment]
@jonpday that works out well - we're starting out with the simpler features, such as the payment methods, and then adding back integration with 3rd-party services like Auspost and Eparcel later.

**Comment by ozgeekmum** [comment]
Very keen for this as well - any date in January?

**Comment by chnorton** [comment]
We have just released the first version of the extension for Magento 2, on the very fitting date of Australia Day. :)

The extension has adds in Australian regions, and includes BPAY and direct deposit payment methods. We'll be fleshing out the remaining functionality from the original extension in the near future.

https://www.fontis.com.au/blog/australia-day-2016-extension-release
https://github.com/fontis/australia-mage2

**Comment by jonpday** [comment]
Awesome, thx Chris
​.

FYI, ​
​we have a Magento2 module for Securepay in Code Review currently.

​Cheers,
​Jonathan​
​
