### ISSUE TITLE
Australia post changes to Signature on Delivery codes

### ISSUE THREAD

**Issue by thomashery** [fontis/fontis_australia#64]
As of 2nd April, Auspost we’ll be making some changes to the signature service in eParcel. This means that codes will change and the "isSignatureRequired" field will no longer be a Yes/No field. 

Are you planning on upgrading the module to reflect these changes?

Please see below support materials:
https://auspost.com.au/content/dam/auspost_corp/media/documents/eparcel-shipping-and-tracking-fact-sheet.pdf

![image007](https://cloud.githubusercontent.com/assets/17426881/24177638/d639e78c-0ede-11e7-913f-2e8c8086434b.jpg)

**Comment by chnorton** [comment]
From what I can tell, it will keep working with the old fields for a while. Is there anything which needs to be changed immediately? Or would this be an improvement to the extension to make it compatible with new features?

I'd be happy to review any pull requests which add in the new fields.

**Comment by thomashery** [comment]
I have created a PR as requested. Can this please be looked at?
