### ISSUE TITLE
Why isn't the tracking implemented for Australia Post shipping method ?

### ISSUE THREAD

**Issue by digitalpianism** [fontis/fontis_australia#66]
In the eparcel shipping method we can see that the tracking is properly implemented:

```
public function isTrackingAvailable()
    {
        return true;
    }

    public function getTrackingInfo($tracking)
    {
        $result = $this->getTracking($tracking);

        if ($result instanceof Mage_Shipping_Model_Tracking_Result) {
            if ($trackings = $result->getAllTrackings()) {
                return $trackings[0];
            }
        } elseif (is_string($result) && !empty($result)) {
            return $result;
        }

        return false;
    }
```

However, in the Australia Post shipping method, it's not implemented whereas it should be using the same code (as both eparcel and auspost use the same tracking url aka http://auspost.com.au/track)

So I'm wondering if there's a good reason why this is not implemented ?

**Comment by chnorton** [comment]
This is likely for historical reasons that are no longer relevant. My recollection is that, in the past, only eParcel supported tracking through the website. I don't think there's any reason it couldn't be added to the Australiapost shipping method now.

**Comment by digitalpianism** [comment]
@chnorton awesome let me do a PR then
